"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.pollsRoutes = exports.voiceRoutes = exports.pushRoutes = exports.themeRoutes = exports.matchdaysRoutes = exports.configRoutes = exports.subscriptionsRoutes = exports.messagesRoutes = exports.planillasRoutes = exports.notificationsRoutes = exports.commentsRoutes = exports.rankingRoutes = exports.betsRoutes = exports.matchesRoutes = exports.usersRoutes = exports.authRoutes = exports.tournamentsRoutes = void 0;
var auth_1 = require("./auth");
Object.defineProperty(exports, "authRoutes", { enumerable: true, get: function () { return __importDefault(auth_1).default; } });
var users_1 = require("./users");
Object.defineProperty(exports, "usersRoutes", { enumerable: true, get: function () { return __importDefault(users_1).default; } });
var matches_1 = require("./matches");
Object.defineProperty(exports, "matchesRoutes", { enumerable: true, get: function () { return __importDefault(matches_1).default; } });
var bets_1 = require("./bets");
Object.defineProperty(exports, "betsRoutes", { enumerable: true, get: function () { return __importDefault(bets_1).default; } });
var ranking_1 = require("./ranking");
Object.defineProperty(exports, "rankingRoutes", { enumerable: true, get: function () { return __importDefault(ranking_1).default; } });
var comments_1 = require("./comments");
Object.defineProperty(exports, "commentsRoutes", { enumerable: true, get: function () { return __importDefault(comments_1).default; } });
var notifications_1 = require("./notifications");
Object.defineProperty(exports, "notificationsRoutes", { enumerable: true, get: function () { return __importDefault(notifications_1).default; } });
var planillas_1 = require("./planillas");
Object.defineProperty(exports, "planillasRoutes", { enumerable: true, get: function () { return __importDefault(planillas_1).default; } });
var messages_1 = require("./messages");
Object.defineProperty(exports, "messagesRoutes", { enumerable: true, get: function () { return __importDefault(messages_1).default; } });
var subscriptions_1 = require("./subscriptions");
Object.defineProperty(exports, "subscriptionsRoutes", { enumerable: true, get: function () { return __importDefault(subscriptions_1).default; } });
var config_1 = require("./config");
Object.defineProperty(exports, "configRoutes", { enumerable: true, get: function () { return __importDefault(config_1).default; } });
var theme_1 = require("./theme");
Object.defineProperty(exports, "themeRoutes", { enumerable: true, get: function () { return __importDefault(theme_1).default; } });
var tournaments_1 = require("./tournaments");
Object.defineProperty(exports, "tournamentsRoutes", { enumerable: true, get: function () { return __importDefault(tournaments_1).default; } });
var teams_1 = require("./teams");
Object.defineProperty(exports, "teamsRoutes", { enumerable: true, get: function () { return __importDefault(teams_1).default; } });
var matchdays_1 = require("./matchdays");
Object.defineProperty(exports, "matchdaysRoutes", { enumerable: true, get: function () { return matchdays_1; } });
var imagemail_1 = require("./imagemail");
Object.defineProperty(exports, "imagemailRoutes", { enumerable: true, get: function () { return __importDefault(imagemail_1).default; } });
var push_1 = require("./push");
Object.defineProperty(exports, "pushRoutes", { enumerable: true, get: function () { return __importDefault(push_1).default; } });
var admin_1 = require("./admin");
Object.defineProperty(exports, "adminRoutes", { enumerable: true, get: function () { return admin_1; } });
var voice_1 = require("./voice");
Object.defineProperty(exports, "voiceRoutes", { enumerable: true, get: function () { return __importDefault(voice_1).default; } });
var polls_1 = require("./polls");
Object.defineProperty(exports, "pollsRoutes", { enumerable: true, get: function () { return __importDefault(polls_1).default; } });
//# sourceMappingURL=index.js.map
